### PR TITLE
Map patch and karma cap increase

### PR DESCRIPTION
**Pull request by TheLazyCowboy1**
Why is GitHub not syncingggg

### CODE REVIEW

**Comment by MelonIs45** [comment]
if the karma cap is set based on mods, is it necessary for it to be added to the config? or is that just incase people just want to set the karma cap to something other than 5?

**Comment by TheLazyCowboy1** [comment]
I thought it would be best as a config because:
1. People might have RegionKit installed but not want karma requirements above 5.
2. It's a nice option to have regardless.
3. It might be impossible to complete some randomized campaigns unless DynamicRNG (or whatever the setting is) is on.
4. While it is possible to check if regions are inaccessible and rerandomize until all regions are accessible... that's a lot of extra work.

**Comment by MelonIs45** [comment]
ok that makes sense thank you!

**Comment by MelonIs45** [comment]
I'll try to update this tonight

**Pull request merged**
